Repository kubenav/kubenav, pull requests merged in 2023-01, with the labels that each got.

#464 Fix Continuous Delivery GitHub Action
  .github/workflows/continuous-delivery.yaml
Labels: changelog: fixed

#463 Make Sponsor Banner Less Annoying
  lib/repositories/app_repository.dart
  lib/repositories/sponsor_repository.dart
  lib/widgets/settings/settings/settings_info.dart
  lib/widgets/settings/settings/settings_sponsor.dart
  lib/widgets/settings/settings/sponsor/settings_sponsor_actions.dart
  lib/widgets/settings/settings/sponsor/settings_sponsor_subscribe.dart
  pubspec.yaml
Labels: changelog: fixed

#465 Improve Custom Icons
  fonts/CustomIcons.ttf
  lib/utils/custom_icons.dart
  lib/widgets/settings/settings/settings_info.dart
  utils/images/custom-icons/browser.svg
  utils/images/custom-icons/config.json
  utils/images/custom-icons/custom-icons.afdesign
  utils/images/custom-icons/github.svg
  utils/images/custom-icons/license.svg
  utils/images/custom-icons/paypal.svg
  utils/images/custom-icons/twitter.svg
  utils/images/custom-icons/version.svg
Labels: changelog: changed

#466 Fix Tooltip Position in Charts
  lib/widgets/home/overview/overview_metric.dart
  lib/widgets/shared/app_prometheus_chart_widget.dart
Labels: changelog: fixed

#468 Fix Show all Pods Running on Node
  lib/widgets/resources/resources_list.dart
  pubspec.yaml
Labels: changelog: fixed

#470 Get Logs for Deployment, DaemonSet and StatefulSet
  lib/widgets/resources/details/details_get_logs.dart
  lib/widgets/resources/details/details_get_logs_pods.dart
  lib/widgets/resources/resource_details.dart
Labels: changelog: added

#472 fix(aws): persist role arn
  lib/models/cluster_provider.dart
Labels: changelog: fixed

#474 Add Full Height Modal Setting
  lib/repositories/app_repository.dart
  lib/widgets/resources/details/details_live_metrics.dart
  lib/widgets/settings/settings.dart
  lib/widgets/shared/app_bottom_sheet_widget.dart
  lib/widgets/shared/app_terminals_widget.dart
Labels: changelog: added

#475 Disable Navigation to Current Page
  lib/widgets/settings/settings/sponsor/settings_sponsor_subscribe.dart
  lib/widgets/shared/app_bottom_navigation_bar_widget.dart
Labels: changelog: fixed

#478 macOS: Add Homebrew to Path
  macos/Runner/Info.plist
Labels: changelog: fixed

#480 Add Actions for Resources in List View
  lib/widgets/home/overview/overview_events.dart
  lib/widgets/resources/list/clusterrolebinding_list_item.dart
  lib/widgets/resources/list/configmap_list_item.dart
  lib/widgets/resources/list/cronjob_list_item.dart
  lib/widgets/resources/list/daemonset_list_item.dart
  lib/widgets/resources/list/default_list_item.dart
  lib/widgets/resources/list/deployment_list_item.dart
  lib/widgets/resources/list/endpoint_list_item.dart
  lib/widgets/resources/list/event_list_item.dart
  lib/widgets/resources/list/horizontalpodautoscaler_list_item.dart
  lib/widgets/resources/list/ingress_list_item.dart
  lib/widgets/resources/list/job_list_item.dart
  lib/widgets/resources/list/list_item.dart
  lib/widgets/resources/list/list_item_actions.dart
  lib/widgets/resources/list/namespace_list_item.dart
  lib/widgets/resources/list/networkpolicy_list_item.dart
  lib/widgets/resources/list/node_list_item.dart
  lib/widgets/resources/list/persistentvolume_list_item.dart
  lib/widgets/resources/list/persistentvolumeclaim_list_item.dart
  lib/widgets/resources/list/pod_list_item.dart
  lib/widgets/resources/list/poddisruptionbudget_list_item.dart
  lib/widgets/resources/list/replicaset_list_item.dart
  lib/widgets/resources/list/rolebinding_list_item.dart
  lib/widgets/resources/list/secret_list_item.dart
  lib/widgets/resources/list/service_list_item.dart
  lib/widgets/resources/list/serviceaccount_list_item.dart
  lib/widgets/resources/list/statefulset_list_item.dart
  lib/widgets/resources/list/storageclass_list_item.dart
Labels: changelog: added

#481 Re-add Rancher Support
  assets/providers/rancher.svg
  lib/models/cluster_provider.dart
  lib/models/help.dart
  lib/services/providers/rancher_service.dart
  lib/widgets/settings/clusters/settings_add_cluster_rancher.dart
  lib/widgets/settings/clusters/settings_reuse_provider_config_actions.dart
  lib/widgets/settings/providers/settings_provider_actions.dart
  lib/widgets/settings/providers/settings_rancher_provider_config.dart
  utils/images/providers/provider-icons.afdesign
Labels: changelog: added

#482 Add Support for Streaming Logs
  lib/repositories/terminal_repository.dart
  lib/widgets/resources/details/details_get_logs.dart
  lib/widgets/resources/details/details_terminal.dart
  lib/widgets/shared/app_terminals_widget.dart
  pkg/server/handlers.go
  pkg/server/server.go
  pkg/server/streamlogs/streamlogs.go
Labels: changelog: added

#483 Improve Continuous Delivery GHA for macOS
  .github/workflows/continuous-delivery.yaml
Labels: changelog: changed

#485 Use new "useSafeArea" Property for Modals
  lib/utils/showmodal.dart
  lib/widgets/shared/app_actions_widget.dart
  lib/widgets/shared/app_bottom_sheet_widget.dart
  lib/widgets/shared/app_terminals_widget.dart
Labels: changelog: fixed

#487 Fix GHA for macOS Release
  .github/workflows/continuous-delivery.yaml
Labels: changelog: fixed
