Repository kubenav/kubenav, pull requests merged in 2024-08, with the labels that each got.

#715 Add Option to set Propagation Policy for Delete Requests
  lib/widgets/resources/actions/delete_resource.dart
Labels: changelog: added

#717 Update Flutter to Version 3.24.0
  .github/workflows/continuous-delivery.yaml
  CONTRIBUTING.md
  android/app/build.gradle
  go.mod
  go.sum
  ios/Runner/AppDelegate.swift
  pubspec.lock
  pubspec.yaml
Labels: changelog: changed

#719 Adds AWS GovCloud Regions
  lib/services/providers/aws_service.dart
Labels: changelog: added

#721 Add new AWS Spain region to constants
  lib/services/providers/aws_service.dart
Labels: changelog: added

#722 Fix OIDC Provider for Google
  cmd/kubenav/oidc.go
Labels: changelog: fixed

#723 Update Flutter Version to 3.24.1
  .github/workflows/continuous-delivery.yaml
  pubspec.lock
Labels: changelog: changed

#724 Fix OIDC Provider for Azure
  cmd/kubenav/oidc.go
  go.mod
  go.sum
Labels: changelog: fixed
