Repository kubenav/kubenav, pull requests merged in 2024-04, with the labels that each got.

#580 Update Flutter to Version 3.19.5
  .github/workflows/continuous-delivery.yaml
  CONTRIBUTING.md
  android/app/build.gradle
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  android/settings.gradle
  go.mod
  go.sum
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/widgets/home/overview/overview_metric.dart
  lib/widgets/shared/app_prometheus_chart_widget.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  tools.go
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: changelog: changed

#581 Rework Release GitHub Action
  .github/workflows/kubenav.io.yaml
  .github/workflows/release.yaml
Labels: changelog: changed

#583 Drop Files from `.gitignore`
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradlew
  android/gradlew.bat
Labels: changelog: changed

#584 Use Background Threads on iOS
  ios/Runner/KubenavPlugin.swift
Labels: changelog: changed

#587 Add Pull Request and Issue Template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog: added

#588 Adjust Screenshots in Readme
  README.md
  utils/images/repo/github-screenshot.png
Labels: changelog: changed

#589 Sort Helm Revisions
  cmd/kubenav/helm.go
Labels: changelog: changed

#591 Adjust Modal Bottom Sheets
  lib/repositories/app_repository.dart
  lib/utils/showmodal.dart
  lib/widgets/settings/settings.dart
  lib/widgets/shared/app_actions_widget.dart
  lib/widgets/shared/app_bottom_sheet_widget.dart
  lib/widgets/shared/app_terminals_widget.dart
Labels: changelog: changed

#592 Fix Pod Selection for Logs
  lib/widgets/resources/details/details_get_logs_pods.dart
Labels: changelog: fixed

#593 Rename `kubenav.io` Directory to `landing`
  .github/workflows/release.yaml
  landing/CNAME
  landing/auth/google.html
  landing/auth/oidc.html
  landing/css/index.css
  landing/favicon.png
  landing/img/badge-app-store.svg
  landing/img/badge-google-play.svg
  landing/img/icon.png
  landing/img/iphone.png
  landing/img/open-graph.png
  landing/index.html
  landing/privacy.html
Labels: changelog: changed

#594 Use Upstream Version of the `oauth2` Package
  cmd/kubenav/oidc.go
  go.mod
  go.sum
Labels: changelog: changed

#595 Fix Tab Alignment
  lib/widgets/resources/details/details_live_metrics.dart
  lib/widgets/shared/app_terminals_widget.dart
Labels: changelog: fixed

#596 Remove Classic Mode
  lib/repositories/app_repository.dart
  lib/utils/showmodal.dart
  lib/widgets/home/home_clusters.dart
  lib/widgets/home/home_overview.dart
  lib/widgets/plugins/helm/plugin_helm_details.dart
  lib/widgets/plugins/helm/plugin_helm_list.dart
  lib/widgets/plugins/helm/plugin_helm_list_item_actions.dart
  lib/widgets/plugins/plugins.dart
  lib/widgets/plugins/prometheus/plugin_prometheus_details.dart
  lib/widgets/plugins/prometheus/plugin_prometheus_list.dart
  lib/widgets/resources/bookmarks/resources_bookmarks.dart
  lib/widgets/resources/resource_details.dart
  lib/widgets/resources/resources.dart
  lib/widgets/resources/resources_list.dart
  lib/widgets/resources/resources_list_crds.dart
  lib/widgets/settings/settings.dart
  lib/widgets/settings/settings_clusters.dart
  lib/widgets/settings/settings_help.dart
  lib/widgets/settings/settings_namespaces.dart
  lib/widgets/settings/settings_providers.dart
  lib/widgets/shared/app_clusters_widget.dart
  lib/widgets/shared/app_drawer.dart
  lib/widgets/shared/app_resource_actions.dart
Labels: changelog: changed

#598 Add Divider between Action Items
  lib/widgets/shared/app_actions_widget.dart
Labels: changelog: changed

#604 Update Flutter Packages
  pubspec.lock
  pubspec.yaml
Labels: changelog: changed

#601 Sort Helm Releases Alphabetical
  cmd/kubenav/helm.go
Labels: changelog: fixed

#603 Remove `onPlatformBrightnessChanged` Function
  lib/main.dart
  lib/repositories/theme_repository.dart
Labels: changelog: changed

#602 Fix Unnecessary Rerendering
  lib/widgets/resources/resource_details.dart
  lib/widgets/resources/resources_list.dart
Labels: changelog: fixed

#605 Update TPInAppReceipt Library
  ios/Podfile.lock
Labels: changelog: changed

#607 Fix `nil dereference in field selection` Warning
  cmd/kubenav/aws.go
Labels: changelog: fixed

#608 Improve Terminal Handling
  lib/repositories/terminal_repository.dart
  lib/widgets/resources/details/details_get_logs.dart
  lib/widgets/resources/details/details_terminal.dart
  lib/widgets/shared/app_floating_action_buttons_widget.dart
  lib/widgets/shared/app_terminals_widget.dart
Labels: changelog: changed

#609 Helm: Add Support for Release Rollbacks
  android/app/src/main/kotlin/io/kubenav/kubenav/KubenavPlugin.kt
  cmd/kubenav/helm.go
  cmd/kubenav/helm/client.go
  cmd/kubenav/helm/client_getter.go
  go.mod
  go.sum
  ios/Runner/KubenavPlugin.swift
  lib/services/kubernetes_service.dart
  lib/widgets/plugins/helm/plugin_helm_details.dart
  lib/widgets/plugins/helm/plugin_helm_details_rollback.dart
  lib/widgets/plugins/helm/plugin_helm_list.dart
  lib/widgets/shared/app_terminals_widget.dart
Labels: changelog: added

#612 Add `tools.go` File
  cmd/tools/tools.go
  go.mod
Labels: changelog: changed

#614 Fix Alignment of Icon and Text in Title
  lib/widgets/resources/details/details_item.dart
  lib/widgets/settings/settings.dart
  lib/widgets/shared/app_horizontal_list_cards_widget.dart
  lib/widgets/shared/app_prometheus_charts_widget.dart
Labels: changelog: fixed

#615 Add Missing Space Before Volume Mounts
  lib/widgets/resources/details/details_container.dart
Labels: changelog: fixed

#616 Add Clear Button to Filter Field
  lib/widgets/resources/resources_list.dart
  lib/widgets/resources/resources_list_crds.dart
Labels: changelog: added

#613 Add Missing API Declaration
  ios/PrivacyInfo.xcprivacy
  ios/Runner.xcodeproj/project.pbxproj
  pubspec.yaml
Labels: changelog: fixed

#618 Add Home Page Configuration
  lib/repositories/app_repository.dart
  lib/widgets/home/home_overview.dart
  lib/widgets/home/overview/overview_events.dart
  lib/widgets/settings/settings.dart
  lib/widgets/settings/settings/settings_home_page.dart
Labels: changelog: added

#619 Allow Text Selection in Code Views
  lib/widgets/plugins/helm/plugin_helm_details_manifest.dart
  lib/widgets/plugins/helm/plugin_helm_details_template.dart
  lib/widgets/plugins/helm/plugin_helm_details_values.dart
  lib/widgets/resources/details/details_show_yaml.dart
Labels: changelog: changed

#621 Add Clear Button to Filter Field
  lib/widgets/resources/resources_list.dart
  lib/widgets/resources/resources_list_crds.dart
Labels: changelog: added

#623 Use `kubectl.kubernetes.io/default-container` Annotation
  lib/widgets/resources/details/details_get_logs.dart
  lib/widgets/resources/details/details_terminal.dart
Labels: changelog: added

#625 Adjust Naming in Flux Plugin
  lib/widgets/plugins/flux/plugin_flux.dart
  lib/widgets/plugins/flux/plugin_flux_details.dart
  lib/widgets/plugins/flux/plugin_flux_details_reconcile.dart
  lib/widgets/plugins/flux/plugin_flux_details_resume.dart
  lib/widgets/plugins/flux/plugin_flux_details_suspend.dart
  lib/widgets/plugins/flux/plugin_flux_list.dart
  lib/widgets/plugins/flux/plugin_flux_list_item_actions.dart
  lib/widgets/plugins/flux/plugin_flux_list_resources.dart
  lib/widgets/plugins/flux/plugin_flux_resources.dart
  lib/widgets/plugins/flux/resources.dart
  lib/widgets/plugins/helm/plugin_helm_list.dart
  lib/widgets/plugins/plugins.dart
Labels: changelog: changed

#626 Adjust `KubernetesService().getRequest()` Function
  lib/services/kubernetes_service.dart
  lib/widgets/home/overview/overview_events.dart
  lib/widgets/home/overview/overview_metric.dart
  lib/widgets/plugins/flux/plugin_flux_details.dart
  lib/widgets/plugins/flux/plugin_flux_list.dart
  lib/widgets/plugins/prometheus/plugin_prometheus_details.dart
  lib/widgets/plugins/prometheus/plugin_prometheus_list.dart
  lib/widgets/resources/details/details_get_logs_pods.dart
  lib/widgets/resources/details/details_live_metrics.dart
  lib/widgets/resources/details/details_resources_preview.dart
  lib/widgets/resources/details/pod_details_item.dart
  lib/widgets/resources/resource_details.dart
  lib/widgets/resources/resources_list.dart
  lib/widgets/resources/resources_list_crds.dart
  lib/widgets/shared/app_namespaces_widget.dart
Labels: changelog: changed

#627 feat: Corrected grammar
  lib/widgets/resources/details/details_resources_preview.dart
Labels: changelog: fixed
