Repository kubenav/kubenav, pull requests merged in 2025-03, with the labels that each got.

#767 Update Flutter Version to 3.29.0 and Go Version to 1.24.0
  .github/workflows/continuous-delivery.yaml
  .gitignore
  CONTRIBUTING.md
  android/.gitignore
  go.mod
  go.sum
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  pubspec.lock
  pubspec.yaml
Labels: changelog: changed

#763 Add new AWS Region ap-southeast-5
  lib/services/providers/aws_service.dart
Labels: changelog: added

#769 OIDC: Add Option to Disable Default Scopes
  android/app/src/main/kotlin/io/kubenav/kubenav/KubenavPlugin.kt
  cmd/kubenav/oidc.go
  ios/Podfile.lock
  ios/Runner/KubenavPlugin.swift
  lib/models/cluster_provider.dart
  lib/repositories/clusters_repository.dart
  lib/services/providers/oidc_service.dart
  lib/widgets/settings/providers/reauthenticate/settings_reauthenticate_oidc_provider_config.dart
  lib/widgets/settings/providers/settings_oidc_provider_config.dart
Labels: changelog: added

#778 Change State Token Length to 12 Characters
  lib/widgets/settings/providers/settings_oidc_provider_config.dart
Labels: changelog: fixed

#779 Update Flutter Version to 3.29.2
  .github/workflows/continuous-delivery.yaml
  CONTRIBUTING.md
Labels: changelog: changed

#780 Catch Panics when Creating a New Kubernetes Client
  cmd/kubenav/kube/kube.go
Labels: changelog: fixed

#781 Improve Pod Status for Restarts
  lib/widgets/resources/resources/resources_pods.dart
Labels: changelog: changed
